#!/usr/bin/env bash
# comment
sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get install haproxy=1.8.\* -y

printf %s 'backend web-backend
        balance roundrobin
        server 4799-web-01 34.203.28.29:80 check
        server 4799-web-02 34.224.214.248:80 check
        
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
