#!/usr/bin/env bash
#change port
regex_existing_ipv4_config="listen\s.[0-9]\sdefault_server"
port_80_ipv4_config="listen 80 default_server"

regex_existing_ipv6_config="listen\s\[::\]:.[0-9]\sdefault_server"
port_80_ipv6_config="listen [::]:80 default_server"

sed -i "s/$regex_existing_ipv4_config/$port_80_ipv4_config/" /etc/nginx/sites-available/default

sed -i "s/$regex_existing_ipv6_config/$port_80_ipv6_config/" /etc/nginx/sites-available/default

service nginx restart
